"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 1.9.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ifk#-_=&y&1-lkd!esxtw4@l7=(&77e6nalb7udza8fv@o1tlq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'admin_reorder',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ABET_DB',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'admin_reorder.middleware.ModelAdminReorder',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {

         'ENGINE': 'django.db.backends.sqlite3',
         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),

        #'ENGINE': 'django.db.backends.mysql',
        #'NAME': 'jkohann_sp16',
        #'USER': 'jkohann',
        #'PASSWORD': 'Kahrozah9xohbo',
        #'HOST': 'dbs.eecs.utk.edu'
    }
}
'''
# LDAP Authentication
# https://pythonhosted.org/django-auth-ldap/install.html

# Baseline configuration.
AUTH_LDAP_SERVER_URI = "ldap://@ldap.utk.edu"
AUTH_LDAP_BIND_DN = "dc=tennessee,dc=edu"
AUTH_LDAP_USER_SEARCH = LDAPSearch("ou=users,",
    ldap.SCOPE_SUBTREE, "(uid=%s)")

AUTHENTICATION_BACKENDS = (
	'django_auth_ldap.backend.LDAPBackend',
	'django.contrib.auth.backends.ModelBackend',
)
'''

#manages the ordering of models on the admin page
ADMIN_REORDER = (
    # Keep original label and models
    'sites',

    {'app': 'ABET_DB', 'label': 'ABET: Per-Semester Information', 'models': ('ABET_DB.sections', 'ABET_DB.courseOutcomes')},
    
    {'app': 'ABET_DB', 'label': 'ABET: Infrequently Changed Information', 'models': ('ABET_DB.performanceLevels', 'ABET_DB.studentOutcomes', 'ABET_DB.professors', 'ABET_DB.courses')},
    
    {'app': 'ABET_DB', 'label': 'ABET: Other Information', 'models': ('ABET_DB.outcomeData', 'ABET_DB.performanceIndicators', 'ABET_DB.rubrics')}
)


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'
