# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-24 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courseOutcomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narrativeSummary', models.CharField(default='', max_length=512, verbose_name='Narrative Summary')),
            ],
            options={
                'verbose_name': 'Outcome-Section Mappings',
                'verbose_name_plural': 'Outcome-Section Mappings',
            },
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=512, verbose_name='Course Name')),
                ('description', models.CharField(default='', max_length=512)),
            ],
            options={
                'verbose_name': 'Courses',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='outcomeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberAchieved', models.IntegerField(default=0, verbose_name='Number Achieved')),
                ('outcome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ABET_DB.courseOutcomes', verbose_name='Outcome')),
            ],
            options={
                'verbose_name': 'Outcome Data',
                'verbose_name_plural': 'Outcome Data',
            },
        ),
        migrations.CreateModel(
            name='performanceIndicators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=512)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=5)),
                ('description', models.CharField(default='', max_length=512)),
                ('outcome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ABET_DB.courseOutcomes')),
            ],
            options={
                'verbose_name': 'Performance Indicators',
                'verbose_name_plural': 'Performance Indicators',
            },
        ),
        migrations.CreateModel(
            name='performanceLevels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievementLevel', models.IntegerField(default=0, verbose_name='Achievement Level')),
                ('description', models.CharField(default='', max_length=512)),
            ],
            options={
                'verbose_name': 'Performance Levels',
                'verbose_name_plural': 'Performance Levels',
            },
        ),
        migrations.CreateModel(
            name='professors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netID', models.CharField(default='', max_length=512, verbose_name='Net ID')),
                ('fn', models.CharField(default='', max_length=512, verbose_name='First Name')),
                ('ln', models.CharField(default='', max_length=512, verbose_name='Last Name')),
            ],
            options={
                'verbose_name': 'Professors',
                'verbose_name_plural': 'Professors',
            },
        ),
        migrations.CreateModel(
            name='rubrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradeTopBound', models.IntegerField(null=True, verbose_name='Upper Grade Bound')),
                ('gradeLowerBound', models.IntegerField(null=True, verbose_name='Lower Grade Bound')),
                ('numStudents', models.IntegerField(null=True, verbose_name='Number of Students')),
                ('description', models.CharField(max_length=512, null=True)),
                ('performanceIndicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ABET_DB.performanceIndicators')),
                ('performanceLevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ABET_DB.performanceLevels', verbose_name='Performance Level')),
            ],
            options={
                'verbose_name': 'Rubrics',
                'verbose_name_plural': 'Rubrics',
            },
        ),
        migrations.CreateModel(
            name='sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2016)),
                ('semester', models.CharField(choices=[('summer', 'Summer'), ('fall', 'Fall'), ('spring', 'Spring')], default='spring', max_length=6)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ABET_DB.courses')),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ABET_DB.professors')),
            ],
            options={
                'verbose_name': 'Sections',
                'verbose_name_plural': 'Sections',
            },
        ),
        migrations.CreateModel(
            name='studentOutcomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcomeLetter', models.CharField(max_length=3, verbose_name='Outcome Letter')),
                ('description', models.CharField(default='', max_length=512)),
            ],
            options={
                'verbose_name': 'Outcomes',
                'verbose_name_plural': 'Outcomes',
            },
        ),
        migrations.AddField(
            model_name='outcomedata',
            name='performanceLevel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ABET_DB.performanceLevels', verbose_name='Performance Level'),
        ),
        migrations.AddField(
            model_name='courseoutcomes',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ABET_DB.sections'),
        ),
        migrations.AddField(
            model_name='courseoutcomes',
            name='studentOutcome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ABET_DB.studentOutcomes', verbose_name='Outcome'),
        ),
    ]
