# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='outomeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcomeLetter', models.CharField(max_length=3)),
                ('courseName', models.CharField(max_length=48)),
                ('achievementLevel', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('numberAchieved', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StudentOucomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcomeLetter', models.CharField(max_length=3)),
                ('description', models.CharField(max_length=512)),
            ],
        ),
    ]
