# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ABET_DB', '0002_auto_20160216_1857'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='outomeData',
            new_name='outcomeData',
        ),
    ]
