# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABET_DB', '0003_auto_20160216_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='courseOutcomeMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=48)),
                ('outcomeLetter', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='performanceIndicators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=5)),
                ('description', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='performanceLevels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievementLevel', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='piData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentStrengths', models.CharField(max_length=512)),
                ('studentWeaknesses', models.CharField(max_length=512)),
                ('achievementLevel', models.IntegerField(default=0)),
                ('numberAchieved', models.IntegerField(default=0)),
                ('yr', models.IntegerField(default=0)),
                ('semester', models.CharField(choices=[('summer', 'Summer'), ('fall', 'Fall'), ('spring', 'Spring')], default='fall', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='rubrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievementLevel', models.IntegerField(default=0)),
                ('gradeRange', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=512)),
            ],
        ),
        migrations.RenameField(
            model_name='outcomedata',
            old_name='year',
            new_name='yr',
        ),
        migrations.AddField(
            model_name='outcomedata',
            name='semester',
            field=models.CharField(choices=[('summer', 'Summer'), ('fall', 'Fall'), ('spring', 'Spring')], default='fall', max_length=6),
        ),
    ]
