# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-03 23:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ABET_DB', '0004_auto_20160225_0059'),
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crnNumber', models.IntegerField(default=0)),
                ('courseName', models.CharField(max_length=512)),
                ('courseDescription', models.CharField(max_length=512)),
                ('yr', models.IntegerField(default=0)),
                ('semester', models.CharField(choices=[('summer', 'Summer'), ('fall', 'Fall'), ('spring', 'Spring')], default='fall', max_length=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='courseoutcomemap',
            name='courseName',
        ),
        migrations.RemoveField(
            model_name='courseoutcomemap',
            name='outcomeLetter',
        ),
        migrations.RemoveField(
            model_name='outcomedata',
            name='achievementLevel',
        ),
        migrations.RemoveField(
            model_name='outcomedata',
            name='courseName',
        ),
        migrations.RemoveField(
            model_name='outcomedata',
            name='outcomeLetter',
        ),
        migrations.RemoveField(
            model_name='pidata',
            name='achievementLevel',
        ),
        migrations.RemoveField(
            model_name='rubrics',
            name='achievementLevel',
        ),
        migrations.AddField(
            model_name='courseoutcomemap',
            name='performanceIndicator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ABET_DB.performanceIndicators'),
        ),
        migrations.AddField(
            model_name='courseoutcomemap',
            name='studentOutcome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ABET_DB.studentOutcomes'),
        ),
        migrations.AddField(
            model_name='outcomedata',
            name='performanceLevel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ABET_DB.performanceLevels'),
        ),
        migrations.AddField(
            model_name='outcomedata',
            name='studentOutcome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ABET_DB.studentOutcomes'),
        ),
        migrations.AddField(
            model_name='pidata',
            name='performanceIndicator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ABET_DB.performanceIndicators'),
        ),
        migrations.AddField(
            model_name='pidata',
            name='performanceLevel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ABET_DB.performanceLevels'),
        ),
        migrations.AddField(
            model_name='rubrics',
            name='performanceIndicator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ABET_DB.performanceIndicators'),
        ),
        migrations.AddField(
            model_name='rubrics',
            name='performanceLevel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ABET_DB.performanceLevels'),
        ),
        migrations.AlterField(
            model_name='performancelevels',
            name='achievementLevel',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='performancelevels',
            name='description',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='studentoutcomes',
            name='description',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='studentoutcomes',
            name='outcomeLetter',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AddField(
            model_name='courseoutcomemap',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ABET_DB.courses'),
        ),
        migrations.AddField(
            model_name='outcomedata',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ABET_DB.courses'),
        ),
    ]
