# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-28 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ABET_DB', '0012_auto_20160305_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='professors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netID', models.CharField(default='', max_length=512)),
                ('isAdmin', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='pidata',
            name='performanceIndicator',
        ),
        migrations.RemoveField(
            model_name='pidata',
            name='performanceLevel',
        ),
        migrations.RemoveField(
            model_name='outcomedata',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='outcomedata',
            name='yr',
        ),
        migrations.RemoveField(
            model_name='rubrics',
            name='gradeRange',
        ),
        migrations.AddField(
            model_name='performanceindicators',
            name='name',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='performanceindicators',
            name='studentStrengths',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='performanceindicators',
            name='studentWeaknesses',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='rubrics',
            name='gradeLowerBound',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rubrics',
            name='gradeTopBound',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rubrics',
            name='numStudents',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='courseoutcomemap',
            name='studentOutcome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ABET_DB.studentOutcomes'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='courseName',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='outcomedata',
            name='studentOutcome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ABET_DB.studentOutcomes'),
        ),
        migrations.AlterField(
            model_name='performanceindicators',
            name='description',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='performancelevels',
            name='description',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='rubrics',
            name='description',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='studentoutcomes',
            name='description',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.DeleteModel(
            name='piData',
        ),
    ]
