# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-28 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ABET_DB', '0013_auto_20160328_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseoutcomemap',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseoutcomemap',
            name='performanceIndicator',
        ),
        migrations.RemoveField(
            model_name='courseoutcomemap',
            name='studentOutcome',
        ),
        migrations.AddField(
            model_name='courses',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ABET_DB.professors'),
        ),
        migrations.AddField(
            model_name='performanceindicators',
            name='outcome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ABET_DB.studentOutcomes'),
        ),
        migrations.AddField(
            model_name='studentoutcomes',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ABET_DB.courses'),
        ),
        migrations.AlterField(
            model_name='outcomedata',
            name='studentOutcome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ABET_DB.studentOutcomes'),
        ),
        migrations.DeleteModel(
            name='courseOutcomeMap',
        ),
    ]
