# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-28 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ABET_DB', '0014_auto_20160328_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='crnNumber',
        ),
        migrations.AlterField(
            model_name='outcomedata',
            name='studentOutcome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ABET_DB.studentOutcomes'),
        ),
        migrations.AlterField(
            model_name='performanceindicators',
            name='outcome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ABET_DB.studentOutcomes'),
        ),
    ]
